baseURL = "https://www.fergusfettes.com/schau-radio/"
languageCode = "en-us"
title = "Schau Radio"
theme = "hugrid"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"


[params]
    # Meta
    title = "Schau Radio"
    subtitle = "_schauradio"
    author = "__schau"
    description = "__schau will run a radio show from here"
    keywords = "__scahu, radio, art, Vienna"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "TO THE STREEEEEEEM"

    # Footer text
    footertext = "Made."
