baseURL = "https://radio.schau-wien.at"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "frances"

publishDir = 'docs'

[params]
    # Meta
    name = "Schau Radio"
    author = "__schau"
    description = "__schau will run a radio show from here"
    keywords = "__scahu, radio, art, Vienna"

    # Preview container button text
    buttontext = "TO THE STREEEEEEEM"
    buttontext2 = "2 THE STREEEEEEEM"
